# Generated by Django 5.2.9 on 2025-12-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertypage',
            name='garage_spaces',
            field=models.IntegerField(default=0),
        ),
    ]
